### ISSUE TITLE
process.env

### ISSUE THREAD

**Issue by PabloBonales** [Icestorm05/lastfm-discord-status#1]
![image](https://user-images.githubusercontent.com/82935000/117768268-038bfe00-b1e7-11eb-9927-786194100aa0.png)

**Comment by transbianskylah** [comment]
I have the same issue, can't seem to figure it out

**Comment by manksalot** [comment]
I hit the same error and realized I hadn't set LAST_FM_SECRET .

**Comment by stvv0000** [comment]
hello! can someone please help me, i can't understand how to make it works... I've done everything that's written in the "First Steps", i download zip from here, unpack it, install nodejs, then open cmd in that folder and type "npm start" and it's does not work...



}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-last-fm@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-last-fm@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxx\AppData\Roaming\npm-cache\_logs\2023-04-24T06_36_27_0
07Z-debug.log


0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.14.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle discord-last-fm@1.0.0~prestart: discord-last-fm@1.0.0
6 info lifecycle discord-last-fm@1.0.0~start: discord-last-fm@1.0.0
7 verbose lifecycle discord-last-fm@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle discord-last-fm@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;H:\lastfm-discord-status-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\ProgramData\chocolatey\lib\mpv.install\tools;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Users\xxxx\AppData\Roaming\npm
9 verbose lifecycle discord-last-fm@1.0.0~start: CWD: H:\lastfm-discord-status-master
10 silly lifecycle discord-last-fm@1.0.0~start: Args: [ '/d /s /c', 'node index.js' ]
11 silly lifecycle discord-last-fm@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle discord-last-fm@1.0.0~start: Failed to exec start script
13 verbose stack Error: discord-last-fm@1.0.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid discord-last-fm@1.0.0
15 verbose cwd H:\lastfm-discord-status-master
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v13.14.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error discord-last-fm@1.0.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the discord-last-fm@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by stvv0000** [comment]
upd. i also copy "node_modules" folder in 
lastfm-discord-status folder, as in [PabloBonales](https://github.com/PabloBonales) screenshot. should it have been copied there?

**Comment by Jam0526** [comment]
Not sure if anyone checks this anymore but @PabloBonales your issue is that you named the file '**process.env**' instead of just '**.env**'
after changing the file name to **.env** make sure that you have also added LAST_FM_SECRET='Enter your Last.fm Shared Secret' to the **.env** file because it is not in the README
